# config.yml
---
- name: Set the host 
  shell: tower-cli config host {{ awx_host }} 

- name: Set the username
  command: tower-cli config username {{ awx_username }}

- name: Set the password
  command: tower-cli config password {{ awx_password }} 

- name: Set verify SSL
  command: tower-cli config verify_ssl {{ awx_verify_ssl }}

