# config.yml
---
- name: Set the host 
  shell: tower-cli config host {{ tower_host }} 

- name: Set the username
  command: tower-cli config username {{ tower_username }}

- name: Set the password
  command: tower-cli config password {{ tower_password }} 

- name: Set verify SSL
  command: tower-cli config verify_ssl {{ tower_verify_ssl }}

