- name: Create credentials
  command: >
     tower-cli credential create
       --name '{{ item.name }}'
       --description '{{ item.description }}'
       --credential-type '{{ item.credential_type }}'
       --inputs "{{ item.inputs }}" 
       --organization '{{ item.organization }}'
       --team '{{ item.team }}'
  with_items: '{{ credentials }}'

